config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#home'
  get "top" => 'homes#top'
  get "setting" => 'homes#setting'
  get "policy" => 'homes#policy'
  get "terms" => 'homes#terms'
  get "info" => 'homes#info'
  get "home" => 'homes#home'
  get 'search' => 'homes#top'
  get "receive" => 'rules#receive'
  get "approval/:id" => 'rules#approval', as: "approval" #as:""でURLはapprovalとしつつ、 receive.htmlに送っているStandbyのid(@standbyRuleとして取得している)も参照できるような記載の仕方
  get "denial/:id" => 'rules#denial', as: "denial"
  get "forgive/:id" => 'penalties#forgive', as:"forgive" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているStandbyのid(@standbyPenaltiesとして取得している)も参照できるような記載の仕方
  get "forbid/:id" => 'penalties#forbid', as:"forbid"
  get "accept/community/:community_id/user/:id" => "communities#accept", as:"accept" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているCommunityUserのid(@unacceptedUsersとして取得している)も参照できるような記載の仕方
  get "decline/community/:community_id/user/:id" => "communities#decline", as:"decline"

  resources :users do
    resources :notes
  end
  resources :communities do #URLがcommunityディレクトリ配下にrules、mottos、usersがくる
    get "articles" => 'articles#index'
    resources :goals do
      get "achieved" => 'goals#achieved'
      get "unachieved" => 'goals#unachieved'
    end
    resources :meetings do
      get "pre_edit" => 'meetings#pre_edit'
    end
    resources :rules do
      get "execute" => 'rules#execute' #ルール実行画面への遷移
      post "execute" => 'rules#execute_create' #ルール実行申請。standbyテーブルにテーブルを新しく作成。
    end
    get "new_positive_rule" => 'rules#new_positive'
    post "create_positive" => 'rules#create_positive'
    get "new_negative_rule" => 'rules#new_negative'
    post "create_negative" => 'rules#create_negative'
    resources :mottos
    resources :privileges do
      get "execute" => 'privileges#execute' #今すぐ受けられる特典を「実行」したときのアクション
    end
    resources :penalties do
      get "execute" => 'penalties#execute'
      post "execute" => 'penalties#execute_create'
    end
    resources :users do
      get "mypage" => "users#mypage"
      resources :roles
    end
    resources :records, only: [:index, :show]
    get "join_request" => "communities#join_request"
    delete "out" => "communities#out"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable and :validatable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable
  #アソシエーション
  has_many :community_users, dependent: :destroy
  has_many :communities, through: :community_users
  has_many :goals
  has_many :rule_users
  has_many :rules, through: :rule_users
  has_many :rules
  has_many :mottos
  has_many :standbies
  has_many :penalties
  has_many :privileges
  has_many :records
  has_many :roles, dependent: :destroy
  has_many :meeting_users
  has_many :meetings, through: :meeting_users
  has_one_attached :profile_image #ActiveStrageによる画像保存機能

  VALID_PASSWORD_REGEX = /\A[A-Za-z0-9]+\z/ # 正規表現パターンを定義する（例: 半角英数字のみ）

  validates :name, presence: { message: "ユーザーネームを入力してください。" }
  validates :email, presence: { message: "メールアドレスを入力してください。" }
  validates :password, presence: { message: "パスワードを入力してください。"}, on: :create
  validates :password, length: { minimum: 6, message: '6文字以上のパスワードを登録してください。'} , if: -> { password.present? }
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: '半角英数字のみで登録してください。'} , if: -> { password.present? }
  validates :password_confirmation, presence: { message: "パスワード再確認を入力してください。"}, on: :create
  validates_confirmation_of :password, message: 'パスワードが一致していません。'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :community_user, only: [:index, :show]
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :my_page_user, only: [:mypage]

  def index
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @communityUsers = CommunityUser.where(community_id: params[:community_id], status: 1).order("ABS(point) DESC")
    @community = Community.find(params[:community_id])
    @index = "0"
  end

  def show
    @user = CommunityUser.find_by(user_id: params[:id], community_id: params[:community_id]) #community-info表示に利用
    @community = Community.find(params[:community_id])
    @communityUsers = CommunityUser.where(community_id: params[:community_id], status: 1).order("ABS(point) DESC")
    @targetingPositiveRules = Rule.joins(:rule_users).where("rules.community_id = ? and rules.point >= 0", params[:community_id] ).where('rule_users.user_id' => params[:id])
    @targetingNegativeRules = Rule.joins(:rule_users).where("rules.community_id = ? and rules.point < 0", params[:community_id] ).where('rule_users.user_id' => params[:id])
    @executedRules = Standby.where(executed_user_id: params[:id], community_id: @community.id, action_type: "rule", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @finishedPrivileges = Standby.where(executing_user_id: params[:id], community_id: @community.id, action_type: "privilege", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @finishedPenalties = Standby.where(executing_user_id: params[:id], community_id: @community.id, action_type: "penalty", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @roles = Role.where(user_id: params[:id], community_id: @community.id)
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
  end

  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = User.find_by(id: current_user.id)
    if @user.update(user_params)
      @user.profile_image.attach(params[:user][:profile_image])
      redirect_to top_path
    else
      render 'edit'
    end
  end

  def mypage
    @community = Community.find(params[:community_id])
    @user = CommunityUser.find_by(user_id: current_user.id, community_id: @community.id)
    @activePrivileges = Privilege.where("community_id = ? and point <= ?", @community.id, @user.monthly_point) #whereの変異系：community_idが@community.idでpointが@user.monthly_pointのレコード取得。
    @activePenalties = Penalty.where("community_id = ? and -(point) >= ?", @community.id, @user.monthly_point)
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @myRoles = Role.where(user_id: current_user.id, community_id: @community.id)
    @executedRules = Standby.where(executed_user_id: current_user.id, community_id: @community.id, action_type: "rule", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @finishedPrivileges = Standby.where(executing_user_id: current_user.id, community_id: @community.id, action_type: "privilege", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @finishedPenalties = Standby.where(executing_user_id: current_user.id, community_id: @community.id, action_type: "penalty", approval: "true", updated_at: Time.current.all_month).order(updated_at: :desc)
    @communityUsers = CommunityUser.where(community_id: params[:community_id], status: 1).order("ABS(point) DESC")
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end

  def community_params
    params.require(:community).permit(:community_name, :introduction, :owner_id)
  end

  def community_user_params
    params.require(:community_user).permit(:memo)
  end

  def community_user
    community =  Community.find(params[:community_id])
    belongedUser = CommunityUser.find_by(community_id: community.id, user_id: current_user.id)
    unless community.community_users.exists?(user_id: current_user.id) && belongedUser.status == 1
      redirect_to top_path
    end
  end

  def my_page_user
    myPageUser = User.find(params[:user_id])
    unless myPageUser.id == current_user.id
      redirect_to top_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="page-title">個人情報変更</div>
<div>
  <%= form_with model: @user, local:true, class: "form" do |f| %>
    <div class="form-section">
      <label for="inputName", class="form-label">ユーザーネーム</label><span class="form-note">必須</span>
      <div><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ユーザー名", class: "form-area-small" %></div>
      <div id="error_explanation">
        <% if @user.errors.any? && @user.errors.has_key?(:name) %>
          <ul class="all-error-messages">
            <% @user.errors[:name].each do |message| %>
              <li class="each-error-message"><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="form-section">
      <label for="inputEmail", class="form-label">メールアドレス</label><span class="form-note">必須</span>
      <div><%= f.text_field :email, id:"inputEmail", placeholder:"メールアドレス", class: "form-area-small" %></div>
      <div id="error_explanation">
        <% if @user.errors.any? && @user.errors.has_key?(:email) %>
          <ul class="all-error-messages">
            <% @user.errors[:email].each do |message| %>
              <li class="each-error-message"><%= message %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="form-section">
      <label for="inputImage", class="form-label">プロフィール画像</label><span class="form-note-optional">任意</span>
      <div>
        <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image.variant(resize: "120x120") %>
        <% else %>
          <%= image_tag("f_f_event_98_s512_f_event_98_0bg.jpg", style: "width: 120px; height: 120px;") %>
        <% end %>
      </div>
      <div><%= f.file_field :profile_image, placeholder: "画像を選択してください", class: "form-check-box-label" %></div>
    </div>
    <div class="submittion">
      <div><%= f.submit "編集完了", class: "done-btn" %></div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="members-list-all">
      <div class="members-list-left">
        <div class="community-all-members-wrapper">
          <div class="community-all-members">
            <% @communityUsers.each do |communityUser| %>
              <% if communityUser.user_id == current_user.id %>
                <%= link_to community_user_mypage_path(@community.id, communityUser.user.id), class: "community-member-sum-cta" do %>
                  <div class="community-member-sum">
                    <div class="community-member-sum-left">
                      <div>
                        <% if communityUser.user.profile_image.attached? %>
                          <%= image_tag communityUser.user.profile_image.variant(gravity: :center, resize:"88x88^", crop:"88x88+0+0"), class: "community-member-profile-image" %>
                        <% else %>
                          <%= image_tag("f_f_event_98_s512_f_event_98_0bg.jpg", style: "width: 88px; height: 88px;", class: "community-member-profile-image") %>
                        <% end %>
                      </div>
                      <div class="community-member-name">
                        <%= communityUser.user.name %>
                      </div>
                    </div>
                    <div class="community-member-sum-right">
                      <div class="member-all-roles-wrapper">
                        <div class="member-all-roles">
                          <% roles = Role.where(community_id: @community.id, user_id: communityUser.user_id) %>
                          <% if roles.present? %>
                            <% roles.each.with_index(1) do |role, index| %>
                              <div class="member-each-role">
                                <div class="member-each-role-index">役割<%= index %></div>
                                <div class="member-each-role-content"><%= role.content %></div>
                              </div>
                            <% end %>
                          <% else %>
                            <div class="alt-text">まだ役割が設定されていません。</div>
                          <% end %>
                        </div>
                      </div>
                      <div class="member-points">
                        <div class="member-point">
                          <div class="member-point-title">獲得ポイント</div>
                          <div class="member-point-content"><%= communityUser.point %></div>
                        </div>
                        <div class="member-monthly-point">
                          <div class="member-monthly-point-title">累計ポイント</div>
                          <div class="member-monthly-point-content"><%= communityUser.monthly_point %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <%= link_to community_user_path(@community.id, communityUser.user.id), class: "community-member-sum-cta" do %>
                  <div class="community-member-sum">
                    <div class="community-member-sum-left">
                      <div>
                        <% if communityUser.user.profile_image.attached? %>
                          <%= image_tag communityUser.user.profile_image.variant(resize: "88x88"), class: "community-member-profile-image" %>
                        <% else %>
                          <%= image_tag("f_f_event_98_s512_f_event_98_0bg.jpg", style: "width: 88px; height: 88px;", class: "community-member-profile-image") %>
                        <% end %>
                      </div>
                      <div class="community-member-name">
                        <%= communityUser.user.name %>
                      </div>
                    </div>
                    <div class="community-member-sum-right">
                      <div class="member-all-roles-wrapper">
                        <div class="member-all-roles">
                          <% roles = Role.where(community_id: @community.id, user_id: communityUser.user_id) %>
                          <% if roles.present? %>
                            <% roles.each.with_index(1) do |role, index| %>
                              <div class="member-each-role">
                                <div class="member-each-role-index">役割<%= index %></div>
                                <div class="member-each-role-content"><%= role.content %></div>
                              </div>
                            <% end %>
                          <% else %>
                            <div class="alt-text">まだ役割が設定されていません。</div>
                          <% end %>
                        </div>
                      </div>
                      <div class="member-points">
                        <div class="member-point">
                          <div class="member-point-title">獲得ポイント</div>
                          <div class="member-point-content"><%= communityUser.point %></div>
                        </div>
                        <div class="member-monthly-point">
                          <div class="member-monthly-point-title">累計ポイント</div>
                          <div class="member-monthly-point-content"><%= communityUser.monthly_point %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="members-list-right">
        <%= render 'member_comparison' %>
      </div>
    </div>
  </div>

app/views/users/mypage.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
      <div class="members-all">
      <div class="members-left">
        <div class="my-page-all">
          <div class="my-page-top">
            <div class="my-roles">
              <div class="roles-header">
                <div class="section-title">あなたの役割</div>
                <div class="role-new-header">
                  <% if @myRoles.present? %>
                    <%= link_to new_community_user_role_path(@community.id, current_user.id) do %>
                      <i class="fa-regular fa-square-plus"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <% if @myRoles.present? %>
                <div class="my-all-roles-wrapper">
                  <div class="my-all-roles">
                    <% @myRoles.each.with_index(1) do |role, index| %>
                      <div class="my-each-role">
                        <div class="my-each-role-index"><%= index %></div>
                        <div class="my-each-role-content"><%= role.content %></div>
                        <div class="my-each-role-edit-link">
                          <%= link_to edit_community_user_role_path(@community.id, @user.user_id, role.id) do %>
                            <i class="fa-regular fa-pen-to-square"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% else %>
                <div class="alt-text">あなたの役割を明記しましょう！</div>
                <div class="role-new"><%= link_to "役割設定", new_community_user_role_path(@community.id, current_user.id), class: "role-new-cta" %></div>
              <% end %>
            </div>
          </div>
          <div class="my-page-bottom">
              <div class="my-point-detail">
                <div class="my-point-title">今月の獲得ポイント</div>
                <div class="my-point-index">現在のポイント</div>
                <div class="my-point"><%= @user.point %></div>
                <div class="my-all-rules">
                  <% if @executedRules.present? %>
                    <div class="my-all-executed-rules-wrapper">
                      <div class="section-title">今月実行されたルール</div>
                      <div class="my-all-executed-rules">
                        <% @executedRules.each do |standby| %>
                          <div class="my-each-executed-rule">
                            <div class="my-each-executed-rule-content"><%= standby.content %></div>
                            <div class="my-each-executed-rule-point"><%= standby.point %><span class="point-letter">ポイント</span></div>
                          </div>
                        <% end %>
                        <div class="notes"> ※承認したルールのみ反映。</div>
                      </div>
                    </div>
                  <% else %>
                    <div class="alt-text">今月実行されたルールはありません。</div>
                  <% end %>
                </div>
              </div>
              <div class="my-monthly-point-detail">
                <div class="my-monthly-point-title">累計ポイント</div>
                <div class="my-point-index">残りポイント</div>
                <div class="my-monthly-point"><%= @user.monthly_point %></div>
                <div class="my-all-tasks">
                  <div class="my-all-remaining-tasks-wrapper">
                    <% if @activePrivileges.present? || @activePenalties.present? %>
                      <div class="my-all-remaining-tasks">
                        <% if @activePrivileges.present? %>
                          <div class="section-title">取得可能な報酬</div> <!-- 特典のポイントより個人のポイントが高ければ選択肢に現れる -->
                          <div class="my-remaining-privileges">
                            <% @activePrivileges.each do |privilege| %>
                              <div class="my-each-remaining-privilege">
                                <div class="my-each-remaining-privilege-content"><%= privilege.content %></div>
                                <div class="my-each-remaining-privilege-point"><%= privilege.point %><span class="point-letter">ポイント消費</span></div>
                                <div class="my-each-remaining-privilege-execute"><%= link_to "取得完了", community_privilege_execute_path(@community.id, privilege.id), class: "my-each-remaining-privilege-execute-cta" %></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <% if @activePenalties.present? %>
                          <div class="section-title">実行可能なペナルティ</div>
                          <div class="my-remaining-penalties">
                            <% @activePenalties.each do |penalty| %>
                              <div class="my-each-remaining-penalty">
                                <div class="my-each-remaining-penalty-content"><%= penalty.content %></div>
                                <div class="my-each-remaining-penalty-point"><%= penalty.point %><span class="point-letter">ポイント回復</span></div>
                                <div class="my-each-remaining-penalty-execute"><%= link_to '完了許可申請', community_penalty_execute_path(@community.id, penalty.id), class: "my-each-remaining-penalty-execute-cta" %></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <div class="notes">
                          ※残りポイントは翌月に繰り越されます。<br>
                          ※ポイントがマイナスの場合、翌月に1.5倍になります。<br>
                          ※報酬の取得後に「取得完了」アクションを忘れないように注意してください。
                        </div>
                      </div>
                    <% else %>
                      <div class="alt-text">ポイントを貯めて受けられる報酬を<br>増やしましょう！</div>
                    <% end %>
                  </div>
                  <div class="my-all-done-tasks-wrapper">
                    <% if @finishedPrivileges.present? || @finishedPenalties.present? %>
                      <div class="my-all-done-tasks">
                        <% if @finishedPrivileges.present? %>
                          <div class="section-title">今月取得した報酬</div>
                          <div class="my-done-privileges">
                            <% @finishedPrivileges.each do |standby| %>
                              <div class="my-each-done-privilege">
                                <div class="my-each-done-privilege-content"><%= standby.content %></div>
                                <div class="my-each-done-privilege-point"><%= standby.point %><span class="point-letter">ポイント消費</span></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <% if @finishedPenalties.present? %>
                          <div class="section-title">今月実行したペナルティ</div>
                          <div class="my-done-penalties">
                            <% @finishedPenalties.each do |standby| %>
                              <div class="my-each-done-penalty">
                                <div class="my-each-done-penalty-content"><%= standby.content %></div>
                                <div class="my-each-done-penalty-point"><%= standby.point %><span class="point-letter">ポイント回復</span></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    <% else %>
                      <div class="alt-text">今月実行した報酬とペナルティが<br>表示されます。</div>
                    <% end %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="members-right">
        <%= render 'member_comparison' %>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="members-all">
      <div class="members-left">
        <div class="my-page-all">
          <div class="others-page-top">
            <div class="others-roles">
              <div class="roles-header">
                <div class="section-title">
                  <%= @user.user.name %>の役割
                </div>
              </div>
              <% if @roles.present? %>
                <div class="others-all-roles-wrapper">
                  <div class="others-all-roles">
                    <% @roles.each.with_index(1) do |role, index| %>
                      <div class="others-each-role">
                        <div class="others-each-role-index"><%= index %></div>
                        <div class="others-each-role-content"><%= role.content %></div>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% else %>
                <div class="alt-text">役割が明記されていません。</div>
              <% end %>
            </div>
          </div>
          <div class="others-page-bottom">
              <div class="others-point-detail">
                <div class="others-point-title">今月の獲得ポイント</div>
                <div class="others-point-index">現在のポイント</div>
                <div class="others-point"><%= @user.point %></div>
                <div class="others-all-rules">
                    <div class="others-all-targeting-rules-wrapper">
                      <div class="others-all-targeting-rules">
                        <% if @targetingPositiveRules.present? %>
                          <div class="section-title">対象プラスルール一覧</div>
                          <div class="others-all-targeting-positive-rules">
                            <% @targetingPositiveRules.each do |rule| %>
                              <div class="others-each-targeting-positive-rule">
                                <div class="others-each-targeting-positive-rule-content"><%= rule.content %></div>
                                <div class="others-each-targeting-positive-rule-point"><%= rule.point %><span class="point-letter">ポイント</span></div>
                                <div class="others-each-targeting-positive-rule-execute"><%= link_to "実行", community_rule_execute_path(@community.id, rule.id), class: "others-each-targeting-positive-rule-execute-cta" %></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <% if @targetingNegativeRules.present? %>
                          <div class="section-title">対象マイナスルール一覧</div>
                          <div class="others-all-targeting-negative-rules">
                            <% @targetingNegativeRules.each do |rule| %>
                              <div class="others-each-targeting-negative-rule">
                                <div class="others-each-targeting-negative-rule-content"><%= rule.content %></div>
                                <div class="others-each-targeting-negative-rule-point"><%= rule.point %><span class="point-letter">ポイント</span></div>
                                <div class="others-each-targeting-negative-rule-execute"><%= link_to "実行", community_rule_execute_path(@community.id, rule.id), class: "others-each-targeting-negative-rule-execute-cta" %></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <% unless @targetingPositiveRules.present? && @targetingNegativeRules.present? %>
                          <div class="alt-text">対象ルールがありません。</div>
                        <% end %>
                      </div>
                    </div>
                  <% if @executedRules.present? %>
                    <div class="others-all-executed-rules-wrapper">
                        <div class="section-title">今月実行されたルール</div>
                        <div class="others-all-executed-rules">
                          <% @executedRules.each do |standby| %>
                            <div class="others-each-executed-rule">
                              <div class="others-each-executed-rule-content"><%= standby.content %></div>
                              <div class="others-each-executed-rule-point"><%= standby.point %><span class="point-letter">ポイント</span></div>
                            </div>
                          <% end %>
                          <div class="notes"> ※承認したルールのみ反映。</div>
                        </div>
                    </div>
                  <% else %>
                    <div class="alt-text">今月実行されたルールはありません。</div>
                  <% end %>
                </div>
              </div>
              <div class="others-monthly-point-detail">
                <div class="others-monthly-point-title">累計ポイント</div>
                <div class="others-point-index">残りポイント</div>
                <div class="others-monthly-point"><%= @user.monthly_point %></div>
                <div class="others-all-tasks">
                  <div class="others-all-done-tasks-wrapper">
                    <% if @finishedPrivileges.present? || @finishedPenalties.present? %>
                      <div class="others-all-done-tasks">
                        <% if @finishedPrivileges.present? %>
                          <div class="section-title">今月取得した報酬</div>
                          <div class="others-done-privileges">
                            <% @finishedPrivileges.each do |standby| %>
                              <div class="others-each-done-privilege">
                                <div class="others-each-done-privilege-content"><%= standby.content %></div>
                                <div class="others-each-done-privilege-point"><%= standby.point %><span class="point-letter">ポイント消費</span></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                        <% if @finishedPenalties.present? %>
                          <div class="section-title">今月実行したペナルティ</div>
                          <div class="others-done-penalties">
                            <% @finishedPenalties.each do |standby| %>
                              <div class="others-each-done-penalty">
                                <div class="others-each-done-penalty-content"><%= standby.content %></div>
                                <div class="others-each-done-penalty-point"><%= standby.point %><span class="point-letter">ポイント回復</span></div>
                              </div>
                            <% end %>
                          </div>
                        <% end %>
                      </div>
                    <% else %>
                      <div class="alt-text">今月実行した報酬とペナルティが<br>表示されます。</div>
                    <% end %>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="members-right">
        <%= render 'member_comparison' %>
      </div>
    </div>
  </div>