config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#home'
  get "top" => 'homes#top'
  get "setting" => 'homes#setting'
  get "policy" => 'homes#policy'
  get "terms" => 'homes#terms'
  get "info" => 'homes#info'
  get "home" => 'homes#home'
  get 'search' => 'homes#top'
  get "receive" => 'rules#receive'
  get "approval/:id" => 'rules#approval', as: "approval" #as:""でURLはapprovalとしつつ、 receive.htmlに送っているStandbyのid(@standbyRuleとして取得している)も参照できるような記載の仕方
  get "denial/:id" => 'rules#denial', as: "denial"
  get "forgive/:id" => 'penalties#forgive', as:"forgive" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているStandbyのid(@standbyPenaltiesとして取得している)も参照できるような記載の仕方
  get "forbid/:id" => 'penalties#forbid', as:"forbid"
  get "accept/community/:community_id/user/:id" => "communities#accept", as:"accept" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているCommunityUserのid(@unacceptedUsersとして取得している)も参照できるような記載の仕方
  get "decline/community/:community_id/user/:id" => "communities#decline", as:"decline"

  resources :users do
    resources :notes
  end
  resources :communities do #URLがcommunityディレクトリ配下にrules、mottos、usersがくる
    get "articles" => 'articles#index'
    resources :goals do
      get "achieved" => 'goals#achieved'
      get "unachieved" => 'goals#unachieved'
    end
    resources :meetings do
      get "pre_edit" => 'meetings#pre_edit'
    end
    resources :rules do
      get "execute" => 'rules#execute' #ルール実行画面への遷移
      post "execute" => 'rules#execute_create' #ルール実行申請。standbyテーブルにテーブルを新しく作成。
    end
    get "new_positive_rule" => 'rules#new_positive'
    post "create_positive" => 'rules#create_positive'
    get "new_negative_rule" => 'rules#new_negative'
    post "create_negative" => 'rules#create_negative'
    resources :mottos
    resources :privileges do
      get "execute" => 'privileges#execute' #今すぐ受けられる特典を「実行」したときのアクション
    end
    resources :penalties do
      get "execute" => 'penalties#execute'
      post "execute" => 'penalties#execute_create'
    end
    resources :users do
      get "mypage" => "users#mypage"
      resources :roles
    end
    resources :records, only: [:index, :show]
    get "join_request" => "communities#join_request"
    delete "out" => "communities#out"
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :community

  validates :content, presence: { message: "ゴールを入力してください。" }

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :community_user, only: [:new, :create, :edit, :update, :index, :destroy, :achieved, :unachieved]

  def new
    @community = Community.find(params[:community_id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @goal = Goal.new
  end

  def create
    @community = Community.find(params[:community_id])
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    @goal.community_id = @community.id
    if @goal.deadline.present? && @goal.startline.nil?
      @goal.startline = @goal.created_at
    end
    if @goal.save
      redirect_to community_path(@community.id)
      #履歴登録↓
      newRecord = Record.new
      newRecord.community_id = @community.id
      newRecord.goal_id = @goal.id
      newRecord.content = @goal.content
      newRecord.user_id = current_user.id
      newRecord.updating_user_id = current_user.id
      newRecord.version = 1 #1→作成
      newRecord.action_type = "Goal"
      newRecord.save
    else
      @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
      render 'new'
    end
  end

  def edit
    @community = Community.find(params[:community_id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @goal = Goal.find(params[:id])
  end

  def update
    @community = Community.find(params[:community_id])
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to community_path(@community.id)
      #履歴登録↓
      oldRecord = Record.find_by(goal_id: @goal.id)
      newRecord = Record.new
      newRecord.community_id = @community.id
      newRecord.goal_id = @goal.id
      newRecord.content = @goal.content
      newRecord.user_id = @goal.user_id
      newRecord.updating_user_id = current_user.id
      newRecord.version = oldRecord.version + 1
      newRecord.action_type = "Goal"
      newRecord.save
    else
      @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
      render 'edit'
    end
  end

  def index
    @community = Community.find(params[:community_id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @activeGoal = Goal.find_by(community_id: params[:community_id], status: true)
    @pastGoals = Goal.where(community_id: params[:community_id], status: false).order(updated_at: :desc)
  end

  def destroy
    community = Community.find(params[:community_id])
    goal = Goal.find(params[:id])
    #履歴登録↓
    record = Record.new
    record.community_id = community.id
    record.goal_id = goal.id
    record.content = goal.content
    record.user_id = goal.user_id
    record.updating_user_id = current_user.id
    record.version = 0
    record.action_type = "Goal"
    record.save
    goal.destroy
    redirect_to community_path(community.id)
  end

  def achieved #達成ctaクリック
    community = Community.find(params[:community_id])
    goal = Goal.find_by(community_id: params[:community_id], id: params[:goal_id])
    goal.achievement = true
    goal.status = false
    goal.save
    redirect_to community_goals_path(community.id)
  end

  def unachieved #未達成ctaクリック
    community = Community.find(params[:community_id])
    goal = Goal.find_by(community_id: params[:community_id], id: params[:goal_id])
    goal.status = false
    goal.save
    redirect_to community_goals_path(community.id)
  end

  private

  def goal_params
    params.require(:goal).permit(:community_id, :user_id, :content, :deadline, :startline)
  end

  def community_user
    community =  Community.find(params[:community_id])
    belongedUser = CommunityUser.find_by(community_id: community.id, user_id: current_user.id)
    unless community.community_users.exists?(user_id: current_user.id) && belongedUser.status == 1
      redirect_to top_path
    end
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="goals-all">
      <div class="goals-left">
        <div class="gray-background">
          <div class="section-title">ゴール編集</div>
          <div class="edit-subject-info">
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">内容</div>
              <div class="edit-subject-info-content"><%= @goal.content %></div>
            </div>
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">達成期限</div>
              <% if @goal.deadline.present? %>
                <div class="edit-subject-info-content"><%= @goal.deadline.to_s(:datetime_jp) %></div>
              <% else %>
                <div class="edit-subject-info-content">※指定されていません。</div>
              <% end %>
            </div>
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">開始日時</div>
              <% if @goal.startline.present? %>
                <div class="edit-subject-info-content"><%= @goal.startline.to_s(:datetime_jp) %></div>
              <% else %>
                <div class="edit-subject-info-content"><%= @goal.created_at.to_s(:datetime_jp) %>※作成日</div>
              <% end %>
            </div>
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">期間</div>
              <% if @goal.startline.present? && @goal.deadline.present? %>
                <div class="edit-subject-info-content"><%= ((@goal.deadline - @goal.startline) / 86400).to_i %>日間</div>
              <% elsif @goal.deadline.present? %>
                <div class="edit-subject-info-content"><%= ((@goal.deadline - @goal.created_at) / 86400).to_i %>日間</div>
              <% else %>
                <div class="edit-subject-info-content">※期限が設定されていません。</div>
              <% end %>
            </div>
          </div>
          <%= form_with(model:[@community, @goal], local:true, class: "form") do |f| %>
            <div class="form-section">
              <label><%= f.label :content, "メンバー全員で達成したいゴール", class: "form-label" %><span class="form-note">必須</span></label>
              <div>
                <%= f.text_area :content, class: "form-area-small" %>
              </div>
              <div id="error_explanation">
                <% if @goal.errors.any? && @goal.errors.has_key?(:content) %>
                  <ul class="all-error-messages">
                    <% @goal.errors[:content].each do |message| %>
                      <li class="each-error-message"><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">ゴール設定の手順</i>
                <div class="comment-content">
                  <br>
                  <b>①個々の目標の共有</b><br>
                  夫婦双方が、個々に持っている目標や希望を共有しましょう。<br>
                  将来的にどのようなことを達成したいのか、どのような人生を送りたいのかを明確にすることが大切です。<br>
                  <br>
                  <b>②優先順位をつける</b><br>
                  共有した目標や希望に対して、優先順位を付けましょう。<br>
                  どの目標が最も重要で、どの目標がそれに次ぐものなのかを決めることが必要です。<br>
                  <br>
                  <b>③共通の目標の抽出する</b><br>
                  各自の目標や希望を共有し、優先順位をつけたら、共通の目標を抽出しましょう。<br>
                  共通の目標は、双方にとって優先順位の高いものである可能性が高く、達成することで関係がより強固になることがあります。<br>
                  <br>
                </div>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">ゴールが思い浮かばない場合</i>
                <div class="comment-content">
                  <br>
                  <b>①興味や関心事に着目する</b><br>
                  各自が個人的に興味や関心を持っていることを挙げ、それをヒントにゴールを設定することができます。<br>
                  例えば、旅行好きな人ならば、1年以内に3回旅行に行く、海外旅行に行く、などの目標を設定しましょう。<br>
                  <br>
                  <b>②課題に着目する</b><br>
                  各自が個人的に課題として感じていることを挙げ、それをヒントにゴールを設定することができます。<br>
                  例えば、健康に関する課題がある場合は、健康的な食生活を維持する、運動をする、などの目標を設定しましょう。<br>
                  <br>
                  <b>③人生のライフステージに着目する</b><br>
                  各自が現在の人生のライフステージに着目し、それをヒントにゴールを設定することができます。<br>
                  例えば、子育て中の夫婦であれば、子供の教育に関する目標を設定しましょう。<br>
                  <br>
                  <b>④パートナーとの共通の価値観に着目する</b><br>
                  パートナーと共通の価値観に着目し、それをヒントにゴールを設定することができます。<br>
                  例えば、家族との時間を大切にするという共通の価値観がある場合は、家族との時間を増やすことを目標にしましょう。<br>
                  <br>
                </div>
              </div>
            </div>
            <div class="form-section">
              <label><%= f.label :deadline, "ゴール達成期限", class: "form-label" %><span class="form-note-optional">任意</span></label>
              <div>
                <%= f.datetime_field :deadline %>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">期限設定のメリットとデメリット</i>
                <div class="comment-content">
                  <br>
                  <b>メリット① 目標達成に向けた意識が高まる</b><br>
                  ゴールの達成期限を設けることで、目標達成に向けた意識が高まり、モチベーションが向上することがあります。<br>
                  <br>
                  <b>メリット② ゴールの具体性が高まる</b><br>
                  ゴールの達成期限を設けることで、ゴールの具体性が高まります。<br>
                  具体的な期限を設けることで、ゴールに向かって具体的な計画を立てることができます。<br>
                  <br>
                  <b>メリット③ 結果の評価が容易になる</b><br>
                  ゴールの達成期限を設けることで、結果の評価が容易になります。<br>
                  期限が設けられているため、期限内にゴールが達成されたかどうかが判断しやすくなります。<br>
                  <br>
                  <b>デメリット① 達成期限に焦りやストレスを感じる</b><br>
                  達成期限が設けられているため、その期限までにゴールを達成しなければならないという焦りやストレスを感じることがあります。<br>
                  <br>
                  <b>デメリット② ゴールの重要性が薄れる</b><br>
                  達成期限が設けられることで、その期限までにゴールを達成することが目的化され、ゴール自体の重要性が薄れることがあります。<br>
                  <br>
                </div>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">期限を設定したほうが良い場合としないほうがいい場合</i>
                <div class="comment-content">
                  <br>
                  <b>推奨① 長期的な目標に向けたサブゴール</b><br>
                  例えば、10年後に海外旅行に行くために、1年後までに外国語を習得する、3年後までに海外旅行の予算を貯める、など。<br>
                  <br>
                  <b>推奨② 現在抱えている問題を解決するためのゴール</b><br>
                  例えば、健康状態を改善するために1年以内に5キロの減量をする、転職するために1年以内に必要なスキルを身につける、など。<br>
                  <br>
                  <b>推奨③ 緊急かつ重要なタスク</b><br>
                  例えば、納期が迫っているプロジェクトの完了、借金の返済、など。<br>
                  <br>
                  <b>非推奨① 習慣化したいこと</b><br>
                  例えば、毎日30分運動する、1日1冊本を読む、など。<br>
                  習慣化するまでには個人差があり、期限を設けるとストレスになることがあるため、期限を設けずに継続的に取り組むことが重要です。<br>
                  <br>
                  <b>非推奨② 自己成長や学習目標</b><br>
                  例えば、新しい楽器を習得する、外国語を学ぶ、など。<br>
                  学習の速度や達成までの時間に個人差があり、期限を設けることでモチベーションが下がることがあるため、期限を設けない方が良いことがあります。<br>
                  <br>
                </div>
              </div>
            </div>
            <div class="form-section">
              <label><%= f.label :deadline, "ゴール開始日時", class: "form-label" %><span class="form-note-optional">任意</span></label>
              <div>
                <%= f.datetime_field :startline %>
              </div>
            </div>
            <div class="submission">
              <%= f.submit '編集完了', class: "done-btn" %>
              <%= link_to '削除', community_goal_path(@community.id, @goal.id), method: :delete, class: "alt-link-cta" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="goals-right">
        <%= render 'articles/goal_articles' %>
      </div>
    </div>
  </div>

app/views/goals/index.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="goals-all">
      <div class="goals-left">
        <div class="active-goal-wrapper">
          <div class="active-goal">
            <% if @activeGoal.present? %>
              <div class="active-goal-edit">
                <%= link_to edit_community_goal_path(@community.id, @activeGoal.id) do %>
                  <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
              </div>
              <div class="active-goal-content"><%= @activeGoal.content %></p></div>
              <div class="active-goal-deadline">
                <span class="active-goal-deadline-letter">達成期限</span>
                <% if @activeGoal.deadline.present? %>
                  <span class="active-goal-deadline-time"><%= @activeGoal.deadline.to_s(:datetime_jp) %></span>
                  <% if @activeGoal.deadline < Time.now %>
                    <span class="active-goal-deadline-time-expired">期限が過ぎています。</span>
                  <% end %>
                <% else %>
                  <span class="active-goal-deadline-time">なし</span>
                <% end %>
              </div>
              <div class="active-goal-creator">
                <span class="active-goal-creator-title">設定者</span>
                <span class="active-goal-creator-name"><%= @activeGoal.user.name %></span>
              </div>
              <div class="active-goal-achievement">
                <div class="active-goal-achievement-true"><%= link_to "達成", community_goal_achieved_path(@community.id, @activeGoal.id), class: "active-goal-achievement-true-cta" %></div>
                <div class="active-goal-achievement-false"><%= link_to "未達成", community_goal_unachieved_path(@community.id, @activeGoal.id), class: "active-goal-achievement-false-cta" %></div>
              </div>
            <% else %>
              <div class="active-goal-alt-view-wrapper">
                <div class="active-goal-alt-view">
                  <div class="alt-text">コミュニティのメンバー全員で目指すゴールを決めましょう！</div>
                  <div class="goal-new"><%= link_to "ゴール設定", new_community_goal_path(@community.id), class: "dashboard-goal-new-cta" %></div>
                  <!-- ↑dashbordのゴール設定ctaと同じ見た目にしたいのでclass名同様にしてる  -->
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="past-goals">
          <div class="past-goals-header">
            <div class="section-title">過去のゴール</div>
          </div>
          <div class="all-past-goals-wrapper">
            <div class="all-past-goals">
              <% if @pastGoals.present? %>
                <% @pastGoals.each do |goal| %>
                  <div class="each-past-goal">
                    <div class="each-past-goal-left">
                      <div class="each-past-goal-content"><%= goal.content %></div>
                      <div class="each-past-goal-deadline">
                        <div class="each-past-goal-deadline-title">達成期限</div>
                        <div class="each-past-goal-deadline-subject"><%= goal.deadline.to_s(:datetime_jp) %></div>
                      </div>
                    </div>
                    <div class="each-past-goal-right">
                      <div class="each-past-goal-achievement">
                        <% if goal.achievement == true %>
                          <span class="each-past-goal-achievement-true">達成</span>
                        <% else %>
                          <span class="each-past-goal-achievement-false">未達成</span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <div class="alt-text">
                  ゴールはどんどんアップデートしていきましょう！
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="goals-right">
        <%= render 'articles/goal_articles' %>
      </div>
    </div>
  </div>

app/views/goals/new.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="goals-all">
      <div class="goals-left">
        <div class="gray-background">
          <div class="section-title">ゴール新規作成</div>
          <%= form_with(model: [@community, @goal], url: community_goals_path{@community.id}, local: true, class: "form") do |f| %>
            <div class="form-section">
              <label><%= f.label :content, "メンバー全員で達成したいゴール", class: "form-label" %><span class="form-note">必須</span></label>
              <div>
                <%= f.text_area :content, class: "form-area-small" %>
              </div>
              <div id="error_explanation">
                <% if @goal.errors.any? && @goal.errors.has_key?(:content) %>
                  <ul class="all-error-messages">
                    <% @goal.errors[:content].each do |message| %>
                      <li class="each-error-message"><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">ゴール設定の手順</i>
                <div class="comment-content">
                  <br>
                  <b>①個々の目標の共有</b><br>
                  夫婦双方が、個々に持っている目標や希望を共有しましょう。<br>
                  将来的にどのようなことを達成したいのか、どのような人生を送りたいのかを明確にすることが大切です。<br>
                  <br>
                  <b>②優先順位をつける</b><br>
                  共有した目標や希望に対して、優先順位を付けましょう。<br>
                  どの目標が最も重要で、どの目標がそれに次ぐものなのかを決めることが必要です。<br>
                  <br>
                  <b>③共通の目標の抽出する</b><br>
                  各自の目標や希望を共有し、優先順位をつけたら、共通の目標を抽出しましょう。<br>
                  共通の目標は、双方にとって優先順位の高いものである可能性が高く、達成することで関係がより強固になることがあります。<br>
                  <br>
                </div>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">ゴールが思い浮かばない場合</i>
                <div class="comment-content">
                  <br>
                  <b>①興味や関心事に着目する</b><br>
                  各自が個人的に興味や関心を持っていることを挙げ、それをヒントにゴールを設定することができます。<br>
                  例えば、旅行好きな人ならば、1年以内に3回旅行に行く、海外旅行に行く、などの目標を設定しましょう。<br>
                  <br>
                  <b>②課題に着目する</b><br>
                  各自が個人的に課題として感じていることを挙げ、それをヒントにゴールを設定することができます。<br>
                  例えば、健康に関する課題がある場合は、健康的な食生活を維持する、運動をする、などの目標を設定しましょう。<br>
                  <br>
                  <b>③人生のライフステージに着目する</b><br>
                  各自が現在の人生のライフステージに着目し、それをヒントにゴールを設定することができます。<br>
                  例えば、子育て中の夫婦であれば、子供の教育に関する目標を設定しましょう。<br>
                  <br>
                  <b>④パートナーとの共通の価値観に着目する</b><br>
                  パートナーと共通の価値観に着目し、それをヒントにゴールを設定することができます。<br>
                  例えば、家族との時間を大切にするという共通の価値観がある場合は、家族との時間を増やすことを目標にしましょう。<br>
                  <br>
                </div>
              </div>
            </div>
            <div class="form-section">
              <label><%= f.label :deadline, "ゴール達成期限", class: "form-label" %><span class="form-note-optional">任意</span></label>
              <div>
                <%= f.datetime_field :deadline %>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">期限設定のメリットとデメリット</i>
                <div class="comment-content">
                  <br>
                  <b>メリット① 目標達成に向けた意識が高まる</b><br>
                  ゴールの達成期限を設けることで、目標達成に向けた意識が高まり、モチベーションが向上することがあります。<br>
                  <br>
                  <b>メリット② ゴールの具体性が高まる</b><br>
                  ゴールの達成期限を設けることで、ゴールの具体性が高まります。<br>
                  具体的な期限を設けることで、ゴールに向かって具体的な計画を立てることができます。<br>
                  <br>
                  <b>メリット③ 結果の評価が容易になる</b><br>
                  ゴールの達成期限を設けることで、結果の評価が容易になります。<br>
                  期限が設けられているため、期限内にゴールが達成されたかどうかが判断しやすくなります。<br>
                  <br>
                  <b>デメリット① 達成期限に焦りやストレスを感じる</b><br>
                  達成期限が設けられているため、その期限までにゴールを達成しなければならないという焦りやストレスを感じることがあります。<br>
                  <br>
                  <b>デメリット② ゴールの重要性が薄れる</b><br>
                  達成期限が設けられることで、その期限までにゴールを達成することが目的化され、ゴール自体の重要性が薄れることがあります。<br>
                  <br>
                </div>
              </div>
              <div class="comment">
                <i class="fa-solid fa-circle-info">期限を設定したほうが良い場合としないほうがいい場合</i>
                <div class="comment-content">
                  <br>
                  <b>推奨① 長期的な目標に向けたサブゴール</b><br>
                  例えば、10年後に海外旅行に行くために、1年後までに外国語を習得する、3年後までに海外旅行の予算を貯める、など。<br>
                  <br>
                  <b>推奨② 現在抱えている問題を解決するためのゴール</b><br>
                  例えば、健康状態を改善するために1年以内に5キロの減量をする、転職するために1年以内に必要なスキルを身につける、など。<br>
                  <br>
                  <b>推奨③ 緊急かつ重要なタスク</b><br>
                  例えば、納期が迫っているプロジェクトの完了、借金の返済、など。<br>
                  <br>
                  <b>非推奨① 習慣化したいこと</b><br>
                  例えば、毎日30分運動する、1日1冊本を読む、など。<br>
                  習慣化するまでには個人差があり、期限を設けるとストレスになることがあるため、期限を設けずに継続的に取り組むことが重要です。<br>
                  <br>
                  <b>非推奨② 自己成長や学習目標</b><br>
                  例えば、新しい楽器を習得する、外国語を学ぶ、など。<br>
                  学習の速度や達成までの時間に個人差があり、期限を設けることでモチベーションが下がることがあるため、期限を設けない方が良いことがあります。<br>
                  <br>
                </div>
              </div>
            </div>
            <div class="form-section">
              <label><%= f.label :deadline, "ゴール開始日時", class: "form-label" %><span class="form-note-optional">任意</span></label>
              <div>
                <%= f.datetime_field :startline %>
              </div>
            </div>
            <div class="submission">
              <%= f.submit '作成', class: "done-btn"  %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="goals-right">
        <%= render 'articles/goal_articles' %>
      </div>
    </div>
  </div>