config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#home'
  get "top" => 'homes#top'
  get "setting" => 'homes#setting'
  get "policy" => 'homes#policy'
  get "terms" => 'homes#terms'
  get "info" => 'homes#info'
  get "home" => 'homes#home'
  get 'search' => 'homes#top'
  get "receive" => 'rules#receive'
  get "approval/:id" => 'rules#approval', as: "approval" #as:""でURLはapprovalとしつつ、 receive.htmlに送っているStandbyのid(@standbyRuleとして取得している)も参照できるような記載の仕方
  get "denial/:id" => 'rules#denial', as: "denial"
  get "forgive/:id" => 'penalties#forgive', as:"forgive" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているStandbyのid(@standbyPenaltiesとして取得している)も参照できるような記載の仕方
  get "forbid/:id" => 'penalties#forbid', as:"forbid"
  get "accept/community/:community_id/user/:id" => "communities#accept", as:"accept" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているCommunityUserのid(@unacceptedUsersとして取得している)も参照できるような記載の仕方
  get "decline/community/:community_id/user/:id" => "communities#decline", as:"decline"

  resources :users do
    resources :notes
  end
  resources :communities do #URLがcommunityディレクトリ配下にrules、mottos、usersがくる
    get "articles" => 'articles#index'
    resources :goals do
      get "achieved" => 'goals#achieved'
      get "unachieved" => 'goals#unachieved'
    end
    resources :meetings do
      get "pre_edit" => 'meetings#pre_edit'
    end
    resources :rules do
      get "execute" => 'rules#execute' #ルール実行画面への遷移
      post "execute" => 'rules#execute_create' #ルール実行申請。standbyテーブルにテーブルを新しく作成。
    end
    get "new_positive_rule" => 'rules#new_positive'
    post "create_positive" => 'rules#create_positive'
    get "new_negative_rule" => 'rules#new_negative'
    post "create_negative" => 'rules#create_negative'
    resources :mottos
    resources :privileges do
      get "execute" => 'privileges#execute' #今すぐ受けられる特典を「実行」したときのアクション
    end
    resources :penalties do
      get "execute" => 'penalties#execute'
      post "execute" => 'penalties#execute_create'
    end
    resources :users do
      get "mypage" => "users#mypage"
      resources :roles
    end
    resources :records, only: [:index, :show]
    get "join_request" => "communities#join_request"
    delete "out" => "communities#out"
  end

end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users, dependent: :destroy
  has_many :users, through: :community_users
  has_many :rules, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :mottos, dependent: :destroy
  has_many :standbies, dependent: :destroy
  has_many :privileges, dependent: :destroy
  has_many :penalties, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_one_attached :community_image #ActiveStrageによる画像保存機能
  
  validates :community_name, presence: { message: "コミュニティ名を入力してください。" }

  def self.search(search)
    if search != ""
      Community.where('id LIKE(?)', "%#{search}%")
    end
  end

end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :rule_users, dependent: :destroy #ruleが消えたら、rule_userからも対象のruleが含まれるレコードが削除される。
  has_many :users, through: :rule_users
  belongs_to :community
  belongs_to :creating_user, class_name: 'User', foreign_key: :user_id, optional: true
  belongs_to :updating_user, class_name: 'User', foreign_key: :updating_user_id, optional: true
  has_many :standbies
  has_many :records

  validates :content, presence: { message: "内容を入力してください。" }
  validates :point, presence: { message: "ポイントを入力してください。" }
  validate :validate_positive_point, on: :create_positive #create_positiveアクションのみでバリデーション
  validate :validate_negative_point, on: :create_negative #create_negativeアクションのみでバリデーション
  validate :validates_point_abs, on: :update #updateアクションのみでバリデーション
  validates :genre, presence: { message: "ジャンルを選択してください。" }
  validates :user_ids, presence: { message: "対象メンバーを選択してください。" }

  def validate_positive_point
    if point.present? && point.to_i < 1
      errors.add(:point, '1以上の半角数値を入力してください。')
    end
  end

  def validate_negative_point
    if point.present? && point.to_i > -1
      errors.add(:point, '-1以下の半角数値を入力してください。')
    end
  end

  def validates_point_abs
    if point.present? && point.abs < 1
      errors.add(:point, '0以外の半角数値を入力してください。')
    end
  end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController

  before_action :community_user, only: [:index, :new_positive, :new_negative, :create, :destroy, :edit, :update, :execute, :execute_create]

  def index
    @community = Community.find(params[:community_id]) #意味：Communityモデルから該当するidのレコードをfind(探し出す)する。findはidしか引数にできない。paramがないとcontorollerはデータを受け取れない。アクションないでrule_idも呼び出されているので、しっかり[:community_id]を指定。
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    @genres = Rule.distinct.pluck(:genre)
    @selected_genre = params[:genre] || "すべて"
    @rules = Rule.includes(:community).where(community_id: @community.id)
    if @selected_genre != "すべて"
      @rules = @rules.where(genre: @selected_genre)
    end
     # +ポイントのルールをジャンルでソート
    @positiveRules = @rules.where("point > 0").order(:genre)
    # -ポイントのルールをジャンルでソート
    @negativeRules = @rules.where("point <= 0").order(:genre)
  end

  def new_positive
    @rule = Rule.new
    @community = Community.find(params[:community_id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
  end

  def new_negative
    @rule = Rule.new
    @community = Community.find(params[:community_id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
  end

  def create_positive
    @community = Community.find(params[:community_id])
    #ruleレコード保存↓
    @rule = Rule.new(rule_params)
    @rule.user_id = current_user.id #ルール制作者
    @rule.community_id = @community.id
    userIds = params[:rule][:user_ids] #[][]に連続※params[]の意味：送られてきた情報を受け取る。今回のcreateアクションではformに記載された情報をストロングパラメーターとして送っており、それを取得している。
    if userIds.present?
      userIds.each do |user_id| #user_idsで配列されているuser一人一人をruleに関連づける。(RuleUser中間テーブルに保存。)
        user = User.find(user_id.to_i)
        @rule.users << user #関連付ける。
      end
      ruleUsers = RuleUser.where(rule_id: @rule.id) #中間テーブルの各community_idの保存。
      ruleUsers.each do |user|
        user.community_id = params[:community_id]
        user.save
      end
    end
    if @rule.valid?(:create_positive) # バリデーションをチェックする際にコンテキストを指定
      if @rule.save
        newRecord = Record.new
        newRecord.community_id = @community.id
        newRecord.rule_id = @rule.id
        newRecord.content = @rule.content
        newRecord.point = @rule.point
        newRecord.genre = @rule.genre
        newRecord.user_id = current_user.id
        newRecord.updating_user_id = current_user.id
        newRecord.version = 1
        newRecord.action_type = "Rule"
        newRecord.save
        redirect_to community_rules_path(@community.id)
      else
        @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id])
        render 'new_positive'
      end
    else
      @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id])
      render 'new_positive'
    end
  end

  def create_negative
    @community = Community.find(params[:community_id])
    #ruleレコード保存↓
    @rule = Rule.new(rule_params)
    @rule.user_id = current_user.id #ルール制作者
    @rule.community_id = @community.id
    userIds = params[:rule][:user_ids] #[][]に連続※params[]の意味：送られてきた情報を受け取る。今回のcreateアクションではformに記載された情報をストロングパラメーターとして送っており、それを取得している。
    if userIds.present?
      userIds.each do |user_id| #user_idsで配列されているuser一人一人をruleに関連づける。(RuleUser中間テーブルに保存。)
        user = User.find(user_id.to_i)
        @rule.users << user #関連付ける。
      end
      ruleUsers = RuleUser.where(rule_id: @rule.id) #中間テーブルの各community_idの保存。
      ruleUsers.each do |user|
        user.community_id = params[:community_id]
        user.save
      end
    end
    if @rule.valid?(:create_negative) # バリデーションをチェックする際にコンテキストを指定
      if @rule.save
        newRecord = Record.new
        newRecord.community_id = @community.id
        newRecord.rule_id = @rule.id
        newRecord.content = @rule.content
        newRecord.point = @rule.point
        newRecord.genre = @rule.genre
        newRecord.user_id = current_user.id
        newRecord.updating_user_id = current_user.id
        newRecord.version = 1
        newRecord.action_type = "Rule"
        newRecord.save
        redirect_to community_rules_path(@community.id)
      else
        @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
        render 'new_negative'
      end
    else
      @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id])
      render 'new_negative'
    end
  end

  def destroy
    @community = Community.find(params[:community_id])
    rule = Rule.find(params[:id])
    #履歴登録↓
    newRecord = Record.new
    newRecord.community_id = @community.id
    newRecord.rule_id = rule.id
    newRecord.content = rule.content
    newRecord.point = rule.point
    newRecord.genre = rule.genre
    newRecord.user_id = rule.user_id
    newRecord.updating_user_id = current_user.id
    newRecord.version = 0
    newRecord.action_type = "Rule"
    newRecord.save
    rule.destroy
    redirect_to community_rules_path(@community.id)
  end

  def edit
    @community = Community.find(params[:community_id])
    @rule = Rule.find(params[:id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
    render "edit"
  end

  def update
    @community = Community.find(params[:community_id])
    @rule = Rule.find(params[:id])
    @rule.updating_user_id = current_user.id
    oldUserIds = @rule.users.pluck(:id) #idを配列で取得
    newUserIds = params[:rule][:user_ids]
    if oldUserIds.present?
      oldUserIds.each do |userId|
        user = RuleUser.find_by(rule_id: @rule.id, user_id: userId.to_i)
        user.destroy
      end
    end
    if newUserIds.present?
      newUserIds.each do |userId|
        user = User.find(userId.to_i)
        @rule.users << user #関連付ける。
      end
    end
    ruleUsers = RuleUser.where(rule_id: @rule.id) #中間テーブルの各community_idの保存。
    ruleUsers.each do |user|
      user.community_id = params[:community_id]
      user.save
    end
    if @rule.update(rule_params)
      redirect_to community_rules_path(@community.id)
      #履歴登録↓
      oldRecord = Record.find_by(rule_id: @rule.id)
      newRecord = Record.new
      newRecord.community_id = @community.id
      newRecord.rule_id = @rule.id
      newRecord.content = @rule.content
      newRecord.point = @rule.point
      newRecord.genre = @rule.genre
      newRecord.user_id = @rule.user_id
      newRecord.updating_user_id = current_user.id
      newRecord.version = oldRecord.version + 1
      newRecord.action_type = "Rule"
      newRecord.save
    else
      @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
      render 'edit'
    end
  end

  def execute #ルール実行html表示のアクション
    @community = Community.find(params[:community_id])
    @rule = Rule.find(params[:rule_id])
    @targetUsers = User.joins(:rule_users).where(rule_users: {rule_id: params[:rule_id]})
    @positiveTargetUsers = User.joins(:rule_users).where(rule_users: {rule_id: params[:rule_id]}).where.not(id: current_user.id)
    @negativeTargetUsers = User.joins(:rule_users).where(rule_users: {rule_id: params[:rule_id]})
    @standby = Standby.new
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
  end

  def execute_create #ルール実行htmlから申請、待機テーブルへの登録までのアクション
    @community = Community.find(params[:community_id])
    @rule = Rule.find(params[:rule_id])
    userIds = params[:standby][:executed_user_id]
    detail = params[:standby][:detail]
    if userIds.present?
      userIds.each do |user_id|
        @standby = Standby.new(standby_params)
        @standby.executing_user_id = current_user.id
        @standby.executed_user_id = user_id
        @standby.detail = detail
        @standby.community_id = @community.id
        @standby.rule_id = @rule.id
        @standby.content = @rule.content
        @standby.point = @rule.point
        @standby.action_type = 'rule'
        unless @standby.save
          @targetUsers = User.joins(:rule_users).where(rule_users: {rule_id: params[:rule_id]}).where.not(id: current_user.id)
          @currentUser = CommunityUser.fifnd_by(user_id: current_user.id, community_id: params[:community_id]) #community-info表示に利用
          render 'execute' and return # エラーメッセージを表示してアクションを終了
        end
      end
      @message = "ルールの実行が完了しました。"
      redirect_to community_rules_path(@community.id), notice: @message # 保存が成功した場合のリダイレクト
    end
  end

  def receive #ルール実行申請を受けての承認/否認のアクション(notificationアクションが実装できたら移行)
    @user = current_user
    @standbyRules = Standby.where(action_type: 'rule', executed_user_id: current_user.id, checked: false).order(created_at: :asc) #自分に送られたルール実行
    @standbyPenalties = Standby.where(action_type: 'penalty', executed_user_id: current_user.id, checked: false).order(created_at: :asc) #自分に送られたペナルティ承認依頼
    @unacceptedUsers = CommunityUser.joins(:community).where(status: 0).where(communities: {owner_id: current_user.id}) #自分に送られたコミュティ参加依頼受信
  end

  def approval #ルール承認
    standby = Standby.find(params[:id])
    @community_user = CommunityUser.find_by(user_id: standby.executed_user_id, community_id: standby.community_id)#whereは条件にあっているデータを複数とってくる。今回は1つのデータを取る前提なのでfind_byを利用。
    @community_user.point += standby.point
    @community_user.save
    standby.checked = true #true=確認済み。今後ユーザーが受けてきたルールのカウントをする際には、trueの数をカウントすればいい。
    standby.approval = true
    standby.save
    redirect_to receive_path
  end

  def denial #ルール否認
    standby = Standby.find(params[:id])
    standby.checked = true
    standby.save
    redirect_to receive_path
  end

  private

  def community_params

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/execute.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="rules-all">
      <div class="rules-left">
        <div class="gray-background">
          <div class="page-title">ルール実行</div>
          <div class="edit-subject-info">
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">内容</div>
              <div class="edit-subject-info-content"><%= @rule.content %></div>
            </div>
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">加減ポイント</div>
              <div class="edit-subject-info-content"><%= @rule.point %></div>
            </div>
            <div class="edit-subject-info-section">
              <div class="edit-subject-info-label">ジャンル</div>
              <div class="edit-subject-info-content"><%= @rule.genre %></div>
            </div>
          </div>
          <%= form_with model: @standby, url: community_rule_execute_path(@community.id, @rule.id), local:true, class: "form" do |f| %>
            <div class="form-section">
              <label><%= f.label :executed_user_id, "対象メンバー", class: "form-label" %><span class="form-note">必須</span></label>
              <div class="form-check-box">
                <% if @targetUsers.present? && @rule.point < 0 %>
                  <% @negativeTargetUsers.each do |user| %>
                    <div>
                      <%= check_box_tag "standby[executed_user_id][]", user.id, false, { class: 'form-check-input'} %>
                    </div>
                    <div class="form-check-box-label">
                      <%= user == current_user ? '自己申告' : user.name %>
                    </div>
                  <% end %>
              <% elsif @targetUsers.present? && @rule.point > 0 %>
                  <% @positiveTargetUsers.each do |user| %>
                    <div>
                      <%= check_box_tag "standby[executed_user_id][]", user.id, false, { class: 'form-check-input'} %>
                    </div>
                    <div class="form-check-box-label">
                      <%= user.name %>
                    </div>
                  <% end %>
                <% else %>
                  対象ユーザーが設定されていません。
                <% end %>
              </div>
              <div id="error_explanation">
                <% if @standby.errors.any? && @standby.errors.has_key?(:executed_user_id) %>
                  <ul class="all-error-messages">
                    <% @standby.errors[:executed_user_id].each do |message| %>
                      <li class="each-error-message"><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
              </div>
            </div>
            <div class="form-section">
              <label><%= f.label :detail, "補足", class: "form-label" %><span class="form-note-optional">任意</span></label>
              <div>
                <%= f.text_area :detail, class: "form-area-large" %>
              </div>
            </div>
            <div class="submission"><%= f.submit '対象にルール行使', class: "done-btn" %></div>
          <% end %>
        </div>
      </div>
      <div class="rules-right">
        <%= render 'articles/rule_articles' %>
      </div>
    </div>
  </div>

app/views/rules/index.html.erb
  <div class="community-background">
    <% if @community.community_image.attached? %>
      <%= image_tag @community.community_image %>
    <% end %>
  </div>
  <div class="community-info">
    <%= render 'communities/info', community: @community, currentUser: @currentUser %>
  </div>
  <div class="community-main">
    <div class="rules-all">
      <div class="rules-left">
        <div class="rules-sort">
          <%= form_tag(community_rules_path, method: :get) do %>
            <%= select_tag(:genre, options_for_select(["すべて"] + @genres, @selected_genre), include_blank: false, class: "rules-sort-window") %>
            <%= submit_tag("ジャンル絞り込み", class: "btn btn-primary", class: "done-btn rules-sort-done") %>
          <% end %>
        </div>
        <div class="positive-rules-wrapper">
          <div class="positive-rules-header">
            <div class="section-title">加点ルール</div>
            <div class="rule-new-header">
              <% if @positiveRules.present? %>
                <%= link_to community_new_positive_rule_path(@community.id) do %>
                  <i class="fa-regular fa-square-plus"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          <% if @positiveRules.present? %>
            <div class="all-positive-rules-wrapper">
              <div class="all-positive-rules">
                <% @positiveRules.each do |rule| %>
                  <div class="each-positive-rule">
                    <div class="each-rule-edit">
                      <%= link_to edit_community_rule_path(@community.id, rule.id) do %>
                        <i class="fa-regular fa-pen-to-square"></i>
                      <% end %>
                    </div>
                    <div class="each-rule-content"><%= rule.content %></div>
                    <div class="each-positive-rule-point"><%= rule.point %><span class="point-letter">ポイント</span></div>
                    <div class="each-rule-member-wrapper">
                      <div class="each-rule-member">
                        <div class="each-rule-member-title">対象メンバー</div>
                        <div class="each-rule-members">
                          <% rule.users.each do |user| %>
                            <span class="each-positive-rule-member-name"><%= user.name %></span>
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="each-positive-rule-execute"><%= link_to "実行", community_rule_execute_path(@community.id, rule.id), class: "each-positive-rule-execute-cta" %></div>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="alt-text">ゴール達成に向けてプラスな行動には加点ルールで賞賛しましょう！</div>
            <div class="positive-rule-new"><%= link_to "プラスルール設定", community_new_positive_rule_path(@community.id), class: "positive-rule-new-cta" %></div>
          <% end %>
        </div>
        <div class="negative-rules-wrapper">
          <div class="negative-rules-header">
            <div class="section-title">減点ルール</div>
            <div class="rule-new-header">
              <% if @negativeRules.present? %>
                <%= link_to community_new_negative_rule_path(@community.id) do%>
                  <i class="fa-regular fa-square-plus"></i>
                <% end %>
              <% end %>
            </div>
          </div>
          <% if @negativeRules.present? %>
            <div class="all-negative-rules-wrapper">
              <div class="all-negative-rules">
                <% @negativeRules.each do |rule| %>
                  <div class="each-negative-rule">
                    <div class="each-rule-edit">
                      <%= link_to edit_community_rule_path(@community.id, rule.id) do %>
                        <i class="fa-regular fa-pen-to-square"></i>
                      <% end %>
                    </div>
                    <div class="each-rule-content"><%= rule.content %></div>
                    <div class="each-negative-rule-point"><%= rule.point %><span class="point-letter">ポイント</span></div>
                    <div class="each-rule-member-wrapper">
                      <div class="each-rule-member">
                        <div class="each-rule-member-title">対象メンバー</div>
                        <div class="each-rule-members">
                          <% rule.users.each do |user| %>
                            <span class="each-negative-rule-member-name"><%= user.name %></span>
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="each-negative-rule-execute"><%= link_to "実行", community_rule_execute_path(@community.id, rule.id), class: "each-negative-rule-execute-cta" %></div>
                  </div>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="alt-text">ゴール達成に向けてマイナスな行動を減点ルールで規制しましょう！</div>
            <div class="negative-rule-new"><%= link_to "マイナスルール設定", community_new_negative_rule_path(@community.id), class: "negative-rule-new-cta" %></div>
          <% end %>
        </div>
      </div>
      <div class="rules-right">
        <%= render 'articles/rule_articles' %>
      </div>
    </div>
  </div>

app/views/rules/receive.html.erb
  <div class="page-title"><%= @user.name %>宛の受信BOX</div>
  <div class="executed-rules">
    <div class="executed-rules-header">
      <div class="section-title">受けたルール</div>
    </div>
    <% if @standbyRules.present? %>
      <div class="all-executed-rules-wrapper">
        <div class="all-executed-rules">
          <% @standbyRules.each do |standby| %>
            <div class="each-executed-rule">
                <% if standby.community.community_image.attached? %>
                  <%= image_tag standby.community.community_image, class: "each-executed-rule-background" %>
                <% else %>
                  <%= image_tag("default_background_noword.png", class: "each-executed-rule-background") %>
                <% end %>
                <div class="each-executed-rule-community"><%= link_to standby.community.community_name, community_path(standby.community_id) %></div>
                <div class="each-executed-rule-subject"><%= standby.content %></div>
                <div class="each-executed-rule-point"><%= standby.point %><span class="point-letter">ポイント</span></div>
                <div class="each-executed-rule-executing-user">
                  <div class="each-executed-rule-executing-user-title">申請者</div>
                  <div class="each-executed-rule-executing-user-name"><%= standby.executing_user.name %></div>
                </div>
                <div class="each-executed-rule-date">
                  <div class="each-executed-rule-date-title">実行日時</div>
                  <div class="each-executed-rule-date-subject"><%= standby.created_at.to_s(:datetime_jp) %></div>
                </div>
                <div class="each-executed-rule-note">
                  <div class="each-executed-rule-note-title">補足</div>
                  <div class="each-executed-rule-note-subject">
                    <% if standby.detail.present? %>
                      <%= standby.detail %>
                    <% else %>
                      ※特にありません。
                    <% end %>
                  </div>
                </div>
                <div class="each-executed-rule-submission">
                  <%= link_to "承認する", approval_path(standby), class: "each-executed-rule-submission-cta" %> <!-- 一つのstandbyレコードのみcotrollerに送りたい -->
                  <%= link_to "否認する", denial_path(standby), class: "each-executed-rule-submission-cta" %> <!-- 一つのstandbyレコードのみcotrollerに送りたい -->
                </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="alt-text">あなたに対して実行されたルールはありません。</div>
    <% end %>
  </div>
  <div class="executed-penalties">
    <div class="executed-penalties-header">
      <div class="section-title">ペナルティ完了確認の依頼</div>
    </div>
    <% if @standbyPenalties.present? %>
      <div class="all-executed-penalties-wrapper">
        <div class="all-executed-penalties">
          <% @standbyPenalties.each do |standby| %>
            <div class="each-executed-penalty">
              <% if standby.community.community_image.attached? %>
                <%= image_tag standby.community.community_image, class: "each-executed-penalty-background" %>
              <% else %>
                <%= image_tag("default_background_noword.png", class: "each-executed-penalty-background") %>
              <% end %>
              <div class="each-executed-penalty-community"><%= link_to standby.community.community_name, community_path(standby.community_id) %></div>
              <div class="each-executed-penalty-subject"><%= standby.content %></div>
              <div class="each-executed-penalty-point"><%= standby.point %><span class="point-letter">ポイント回復</span></div>
              <div class="each-executed-penalty-executing-user">
                  <div class="each-executed-penalty-executing-user-title">完了者</div>
                  <div class="each-executed-penalty-executing-user-name"><%= standby.executing_user.name %></div>
                </div>
              <div class="each-executed-penalty-date">
                  <div class="each-executed-penalty-date-title">実行日時</div>
                  <div class="each-executed-penalty-date-subject"><%= standby.created_at.to_s(:datetime_jp) %></div>
                </div>
              <div class="each-executed-penalty-note">
                  <div class="each-executed-penalty-note-title">補足</div>
                  <div class="each-executed-penalty-note-subject">
                    <% if standby.detail.present? %>
                      <%= standby.detail %>
                    <% else %>
                      ※特にありません。
                    <% end %>
                  </div>
                </div>
              <div class="each-executed-penalty-submission">
                  <%= link_to "承認する", forgive_path(standby), class: "each-executed-penalty-submission-cta" %> <!-- 一つのstandbyレコードのみcotrollerに送りたい -->
                  <%= link_to "否認する", forbid_path(standby), class: "each-executed-penalty-submission-cta" %> <!-- 一つのstandbyレコードのみcotrollerに送りたい -->
                </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="alt-text">あなたに送られたペナルティ完了の許可依頼はありません。</div>
    <% end %>
  </div>
  <div class="join-requests">
    <div class="join-requests-header">
      <div class="section-title">オーナーコミュニティへの参加申請</div>
    </div>
    <% if @unacceptedUsers.present? %>
      <div class="all-join-requests-wrapper">
        <div class="all-join-requests">
          <% @unacceptedUsers.each do |user| %>
          <div class="each-join-request">
            <% if user.community.community_image.attached? %>
              <%= image_tag user.community.community_image, class: "each-join-request-background" %>
            <% else %>
              <%= image_tag("default_background_noword.png", class: "each-join-request-background") %>
            <% end %>
            <div class="each-join-request-community"><%=link_to user.community.community_name, community_path(user.community_id) %></div>
            <div class="each-join-request-user">
              <div class="each-join-request-user-title">申請者</div>
              <div class="each-join-request-user-name"><%= user.user.name %></div>
            </div>
            <div class="each-join-request-date">
              <div class="each-join-request-date-title">申請日時</div>
              <div class="each-join-request-date-subject"><%= user.updated_at.to_s(:datetime_jp) %></div>
            </div>
            <div class="each-join-request-submission">
              <%= link_to "許可する", accept_path(user.community_id, user.id), class: "each-join-request-submission-cta" %>
              <%= link_to "拒否する", decline_path(user.community_id, user.id), class: "each-join-request-submission-cta" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="alt-text">参加依頼はありません。</div>
    <% end %>
  </div>