config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#home'
  get "top" => 'homes#top'
  get "setting" => 'homes#setting'
  get "policy" => 'homes#policy'
  get "terms" => 'homes#terms'
  get "info" => 'homes#info'
  get "home" => 'homes#home'
  get 'search' => 'homes#top'
  get "receive" => 'rules#receive'
  get "approval/:id" => 'rules#approval', as: "approval" #as:""でURLはapprovalとしつつ、 receive.htmlに送っているStandbyのid(@standbyRuleとして取得している)も参照できるような記載の仕方
  get "denial/:id" => 'rules#denial', as: "denial"
  get "forgive/:id" => 'penalties#forgive', as:"forgive" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているStandbyのid(@standbyPenaltiesとして取得している)も参照できるような記載の仕方
  get "forbid/:id" => 'penalties#forbid', as:"forbid"
  get "accept/community/:community_id/user/:id" => "communities#accept", as:"accept" #as:""でURLはforgiveとしつつ、 receive.htmlに送っているCommunityUserのid(@unacceptedUsersとして取得している)も参照できるような記載の仕方
  get "decline/community/:community_id/user/:id" => "communities#decline", as:"decline"

  resources :users do
    resources :notes
  end
  resources :communities do #URLがcommunityディレクトリ配下にrules、mottos、usersがくる
    get "articles" => 'articles#index'
    resources :goals do
      get "achieved" => 'goals#achieved'
      get "unachieved" => 'goals#unachieved'
    end
    resources :meetings do
      get "pre_edit" => 'meetings#pre_edit'
    end
    resources :rules do
      get "execute" => 'rules#execute' #ルール実行画面への遷移
      post "execute" => 'rules#execute_create' #ルール実行申請。standbyテーブルにテーブルを新しく作成。
    end
    get "new_positive_rule" => 'rules#new_positive'
    post "create_positive" => 'rules#create_positive'
    get "new_negative_rule" => 'rules#new_negative'
    post "create_negative" => 'rules#create_negative'
    resources :mottos
    resources :privileges do
      get "execute" => 'privileges#execute' #今すぐ受けられる特典を「実行」したときのアクション
    end
    resources :penalties do
      get "execute" => 'penalties#execute'
      post "execute" => 'penalties#execute_create'
    end
    resources :users do
      get "mypage" => "users#mypage"
      resources :roles
    end
    resources :records, only: [:index, :show]
    get "join_request" => "communities#join_request"
    delete "out" => "communities#out"
  end

end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users, dependent: :destroy
  has_many :users, through: :community_users
  has_many :rules, dependent: :destroy
  has_many :goals, dependent: :destroy
  has_many :mottos, dependent: :destroy
  has_many :standbies, dependent: :destroy
  has_many :privileges, dependent: :destroy
  has_many :penalties, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_one_attached :community_image #ActiveStrageによる画像保存機能
  
  validates :community_name, presence: { message: "コミュニティ名を入力してください。" }

  def self.search(search)
    if search != ""
      Community.where('id LIKE(?)', "%#{search}%")
    end
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  before_action :community_owner1, only: [:accept]
  before_action :community_owner2, only: [:edit, :update, :destroy]
  before_action :community_user, only: [:show]

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    @community.owner_id = current_user.id
    @community.users << current_user
    #CommunityUserの当該ユーザーのstatusを1にしたい
    if @community.save!
      community_user = CommunityUser.find_by(user_id: current_user.id, community_id: @community.id)
      community_user.status = 1
      community_user.save
      redirect_to community_path(@community)
    else
      render 'new'
    end
  end

  def index #homes#topに統合
  end

  def show
    @community = Community.find(params[:id])
    @communityUsers = CommunityUser.where(community_id: params[:id], status: 1)
    @user = User.find(current_user.id)
    @nextMeeting = Meeting.find_by(community_id:  params[:id], status: 0) #実施前のMTG
    if @nextMeeting.present? #次のミーティングまでのカウントダウン実装javascriptに使う数値を定義。
      if @nextMeeting.date.present?
        gon.year = @nextMeeting.date.year
        gon.month = @nextMeeting.date.month
        gon.day = @nextMeeting.date.day
      end
    end
    @meetingsInProgress = Meeting.find_by(community_id: params[:id], status: 1) #実施中のMTG
    @rules = Rule.where(community_id: params[:id])
    @mottos = Motto.where(community_id: params[:id])
    @records = Record.where(community_id: params[:id], updated_at: Time.zone.today.ago(30.days)..Time.zone.today.end_of_day).order(updated_at: :desc)
    @goal = Goal.find_by(community_id: params[:id], status: true)
    if @goal.present? #if文にしないとなぜかエラーがでる。
      #deadlineの文字カウントダウン
      gon.deadline = @goal.deadline #gem 'gon'を利用してRailsからJavaScriptオブジェクトに変換
      #deadlineのラインカウントダウン
      if @goal.deadline.present?
        now = Time.current
        if @goal.startline.present? #startが指定されてない時は、updated＿atをスタートにする
          startline = @goal.startline
        else @goal.startline.present?
          startline = @goal.created_at
        end
        total_time = @goal.deadline - startline
        passed_time = now - startline
        remaining_time = @goal.deadline - now
        @passed_ratio = (passed_time.to_f / total_time).clamp(0, 1)
        @remaining_ratio = (remaining_time.to_f / total_time).clamp(0, 1)
      end
    end
    @excutedRules = Standby.where(community_id: params[:id], action_type: "rule", created_at: Time.current.all_month) #今月created_atのデータに絞っている。
    rand = Rails.env.production? ? "rand()" : "RANDOM()" #本番環境なら"rand()"を代入し、それ以外の環境なら"RANDOM()"を代入する。本番環境のMysplではRANDOMは使えないため。
    @coupleAdvice = Advice.where(community_genre: "夫婦・カップル").order(rand).first
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:id]) #community-info表示に利用
    @acceptedUsers = CommunityUser.where(community_id: params[:id], status: 1)
    #ゴールtimelineの表示
  end

  def join_request
    @community = Community.find(params[:community_id])
    @community.users << current_user
    redirect_to top_path
  end

  def accept #rules#receiveで承認許可したユーザーのstatusを1に変える
    user = CommunityUser.find(params[:id])
    user.status = 1
    user.save!
    redirect_to receive_path
  end
  
  def decline
    user = CommunityUser.find(params[:id])
    user.destroy
    redirect_to receive_path
  end

  def out
    @community = Community.find(params[:community_id])
    @community.users.delete(current_user)
    redirect_to top_path
  end

  def destroy
    @community = Community.find(params[:id])
    @community.destroy
    redirect_to top_path
  end

  def edit
    @community = Community.find(params[:id])
    @currentUser = CommunityUser.find_by(user_id: current_user.id, community_id: params[:id]) #community-info表示に利用
  end

  def update
  @community = Community.find(params[:id])
  if @community.update(community_params)
    @community.community_image.attach(params[:community][:community_image])
    if params[:default_background]
      @community.community_image = nil
    end
    redirect_to community_path(@community.id)
  else
    render 'edit'
  end
end

  private

  def community_params
    params.require(:community).permit(:community_name, :introduction, :owner_id, :manual, :genre, :community_image)
  end

  def motto_params
    params.require(:motto).permit(:content)
  end

  def rule_params
    params.require(:rule).permit(:content, :point, :genre, :date)
  end

  def community_owner1
    community = Community.find(params[:community_id])
    unless community.owner_id == current_user.id
      redirect_to top_path
      #「オーナーのみ設定可能です」のnotice
    end
  end

  def community_owner2
    community = Community.find(params[:id])
    unless community.owner_id == current_user.id
      redirect_to top_path
      #「オーナーのみ設定可能です」のnotice
    end
  end

  def community_user
    community =  Community.find(params[:id])
    belongedUser = CommunityUser.find_by(community_id: community.id, user_id: current_user.id)
    unless community.community_users.exists?(user_id: current_user.id) && belongedUser.status == 1
      redirect_to top_path
    end
  end

end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_info.html.erb
  <div class="community-info-contents">
    <ul class="community-navigation-items">
      <li class="community-navigation-item">
        <%= link_to community_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-house"></i>
          <div class="community-navigation-item-letter">ダッシュボード</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_user_mypage_path(community.id, currentUser.user_id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-user"></i>
          <div class="community-navigation-item-letter">マイページ</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_users_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-user-group"></i>
          <div class="community-navigation-item-letter">メンバー</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_rules_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-table-list"></i>
          <div class="community-navigation-item-letter">ルール</div>
        <% end%>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_privileges_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-trophy"></i>
          <div class="community-navigation-item-letter">報酬&ペナルティ</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_mottos_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-scroll"></i>
          <div class="community-navigation-item-letter">スローガン</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_goals_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-bullseye"></i>
          <div class="community-navigation-item-letter">ゴール</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_meetings_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-handshake-simple"></i>
          <div class="community-navigation-item-letter">会議</div>
        <% end %>
      </li>
      <li class="community-navigation-item">
        <%= link_to community_articles_path(community.id), class: "community-navigation-link" do %>
          <i id="community-navigation-item-icon" class="fa-solid fa-book"></i>
          <div class="community-navigation-item-letter">コンテンツ</div>
        <% end %>
      </li>
    </ul>
    <div class="community-basic-info">
      <div class="community-basic-info-name-title">参加中のコミュニティ</div>
      <div class="community-basic-info-name-content"><%= community.community_name %></div>
      <div class="community-basic-info-detail">
        <i class="fa-solid fa-circle-info community-basic-info-detail-cta"></i>
        <div class="community-info-window">
          <div class="community-info-window-section">
            <div class="community-info-window-section-title">コミュニティ名</div>
            <div class="community-info-window-section-content-small">
              <%= community.community_name %>
            </div>
          </div>
          <div class="community-info-window-section">
            <div class="community-info-window-section-title">概要</div>
            <div class="community-info-window-section-content-large">
              <% if community.introduction.present? %>
                <%= safe_join(community.introduction.split("\n"),tag(:br)) %>
              <% else %>
                ※概要はありません。
              <% end%>
            </div>
          </div>
          <div class="community-info-window-section">
            <div class="community-info-window-section-title">利用上の注意点</div>
            <div class="community-info-window-section-content-large">
              <% if community.manual.present? %>
                <%= safe_join(community.manual.split("\n"),tag(:br)) %>
              <% else %>
                ※利用上の注意点はありません。
              <% end%>
            </div>
          </div>
          <div class="community-info-window-submission">
            <% if community.owner_id == current_user.id %>
              <%= link_to "編集する", edit_community_path(community.id), class: "community-info-window-submission-cta" %>
            <% end %>
          </div>
         </div>
      </div>
    </div>
  </div>

app/views/communities/edit.html.erb
  <div class="gray-background">
    <div class="section-title">コミュニティ編集</div>
    <%= form_with(model:[@community], local:true, class: "form") do |f| %>
      <div class="form-section">
        <label><%= f.label :community_name, "コミュニティ名", class: "form-label" %><span class="form-note">必須</span></label>
        <div>
          <%= f.text_field :community_name, placeholder: "250文字まで", class: "form-area-small" %>
        </div>
        <div id="error_explanation">
          <% if @community.errors.any? && @community.errors.has_key?(:community_name) %>
            <ul class="all-error-messages">
              <% @community.errors[:community_name].each do |message| %>
                <li class="each-error-message"><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
      <!-- コミュニティの種類を増やせる段階で公開
      <div class="form-section">
        <label><%= f.label :genre, "コミュニティジャンル", class: "form-label" %><span class="form-note">必須</span></label>
        <div>
          <%= f.select :genre, [["夫婦・カップル", "夫婦・カップル"], ["家族", "家族"], ["兄弟・姉妹", "兄弟・姉妹"], ["友達", "友達"], ["その他", "その他"]], include_blank: "選択してください" %>
        </div>
      </div>
      -->
      <div class="form-section">
        <label><%= f.label :introduction, "コミュニティ概要", class: "form-label" %><span class="form-note-optional">任意</span></label>
        <div>
          <%= f.text_area :introduction, placeholder: "250文字まで", class: "form-area-large" %>
        </div>
      </div>
      <div class="form-section">
        <label><%= f.label :manual, "コミュニティ利用上の注意", class: "form-label" %><span class="form-note-optional">任意</span></label>
        <div>
          <%= f.text_area :manual, placeholder: "独自の使い方があれば記載しましょう！", class: "form-area-large" %>
        </div>
      </div>
      <div class="form-section">
        <label><%= f.label :profile_image, "背景画像", class: "form-label" %><span class="form-note-optional">任意</span></label>
        <div class="community-background-edit">
          <% if @community.community_image.attached? %>
            <%= image_tag @community.community_image %>
          <% else %>
            <%= image_tag("default_background.jpg") %>
          <% end %>
        </div>
        <div><%= f.file_field :community_image, class: "form-select-file" %></div>
        <div class="form-check-box">
          <div><%= check_box_tag :default_background, class: "form-check-box-item" %></div>
          <div><%= label_tag :default_background, "デフォルト画像に戻す", class: "form-check-box-label" %></div>
        </div>
      </div>
      <div class="submission">
        <%= f.submit '編集完了', class: "done-btn" %>
      </div>
    <% end %>
  </div>

app/views/communities/new.html.erb
  <div class="gray-background">
    <div class="section-title">新規コミュニティ作成</div>
    <%= form_with model: @community, url: communities_path, local:true, class: "form" do |f| %> <!-- url: でprefixを利用してcommunities#createを指定。-->
      <div class="form-section">
        <label><%= f.label :community_name, "コミュニティ名", class: "form-label" %><span class="form-note">必須</span></label>
        <div>
          <%= f.text_field :community_name, placeholder: "例）山田夫婦", class: "form-area-small" %>
        </div>
        <div id="error_explanation">
          <% if @community.errors.any? && @community.errors.has_key?(:community_name) %>
            <ul class="all-error-messages">
              <% @community.errors[:community_name].each do |message| %>
                <li class="each-error-message"><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
      <!-- コミュニティの種類を増やせる段階で公開
      <div class="form-section">
        <label><%= f.label :genre, "コミュニティジャンル" %><span class="form-note">必須</span></label>
        <div>
          <%= f.select :genre, [["夫婦・カップル", "夫婦・カップル"], ["家族", "家族"], ["兄弟・姉妹", "兄弟・姉妹"], ["友達", "友達"], ["その他", "その他"]], include_blank: "選択してください" %>
        </div>
      </div>
      -->
      <div class="form-section">
        <label><%= f.label :introduction, "コミュニティ概要", class: "form-label" %><span class="form-note-optional">任意</span></label>
        <div>
          <%= f.text_area :introduction, placeholder: "例）山田夫婦が毎日仲良く過ごすためのルールブック", class: "form-area-large" %>
        </div>
      </div>
      <div class="form-section">
        <label><%= f.label :manual, "コミュニティ利用上の注意", class: "form-label" %><span class="form-note-optional">任意</span></label>
        <div>
          <%= f.text_area :manual, placeholder: "例）2人で話して決めるルール以外は無効。", class: "form-area-large" %>
        </div>
      </div>
      <div class="submission">
        <%= f.submit '作成', class: "done-btn" %>
      </div>
    <% end %>
  </div>